//! vox_web — minimal WebGPU/WASM entry point for Ochroma.
//!
//! This crate is intentionally kept dependency-free of native-only engine crates
//! so it compiles cleanly to wasm32-unknown-unknown.

#[cfg(target_arch = "wasm32")]
use wasm_bindgen::prelude::*;

/// Entry point called automatically by the JS glue generated by wasm-bindgen.
#[cfg(target_arch = "wasm32")]
#[wasm_bindgen(start)]
pub fn wasm_main() {
    console_error_panic_hook::set_once();
    web_sys::console::log_1(&"Ochroma hello_splat loaded".into());
}
