pub mod save;
pub mod vxm;
pub mod materials;
pub mod proc_gs;
pub mod library;
pub mod vxm_v2;
pub mod tile_streamer;
pub mod hot_reload;
pub mod proc_gs_advanced;
pub mod forge_ecs;
pub mod scene_serialize;
pub mod scene_format;
pub mod asset_catalog;
pub mod marketplace;
pub mod neural_compress;
pub mod templates;
pub mod creator_tools;
pub mod osm_import;
pub mod ply_loader;
pub mod spz;
pub mod map_file;
pub mod gi_export;
pub mod gltf_animation;
pub mod gltf_import;
pub mod world_save;
pub mod material_system;
pub mod prefab;
pub mod import_pipeline;
pub mod import_helpers;
pub mod spectral_upsampler;
pub mod spectral_codec;
pub use spectral_upsampler::{SpectralUpsampler, SpectralMaterialDb, SpectralMaterial};
pub mod spectral_capture;
pub use spectral_capture::{LightSpd, SpectralMaterialProfile};
pub use vxm::VxmFileV3;
pub mod colmap_pipeline;
pub use colmap_pipeline::{ColmapPipeline, ColmapPoint, ColmapError};
pub use import_pipeline::{ImportSettings, ImportResult, import_asset};
pub mod vegetation_splatizer;
pub use vegetation_splatizer::{backproject_pca, splatize_vegetation_mesh};
pub mod terrain_splatizer;
pub use terrain_splatizer::{BiomeKind, SpectralTerrainMaterials, biome_to_splat_weights, blend_spectral_terrain};
